### ISSUE TITLE
Weird artifacts when Nautilus is not in focus

### ISSUE THREAD

**Issue by OverclockedSanic** [EliverLara/Kimi#5]
There's a weird color glitch around the icons on nautilus's side bar when not in focus.
![Screenshot](https://i.imgur.com/rVDfIim.png)
Ubuntu 19.10, GNOME 3.34.1

EDIT: This happens regardless of the icon theme used.

**Comment by EliverLara** [comment]
That should be fixed now.

**Comment by OverclockedSanic** [comment]
It happens much less frequently now which is definitely a noticeable improvement, however I'm still getting the same issue in some rare cases when launching the terminal. I'll see if I can reliably reproduce the issue.

**Comment by OverclockedSanic** [comment]
Nevermind, it's gone. Thanks a lot!

**Comment by OverclockedSanic** [comment]
@EliverLara Sorry for bothering again but it turns out there's just a small bug left: if nautilus is not in focus, and you hover over the selected element on the side bar, that same glitch appears again.
